version: 2
updates:
- package-ecosystem: bundler
  directory: "/wpm-api"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.0
    - 1.4.0
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: puma
    versions:
    - 5.2.0
    - 5.2.1
  - dependency-name: loofah
    versions:
    - 2.9.0
  - dependency-name: ffi
    versions:
    - 1.14.2
- package-ecosystem: npm
  directory: "/wpm-client"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: create-react-app
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
